export * from './setups/swagger.setup'
export * from './setups/logger.setup'
export * from './setups/static.setup'
export * from './setups/cors.setup'
export * from './app.factory'
export * from './start-app'
